### ISSUE TITLE
Extract latitude longitudes from data provided

### ISSUE THREAD

**Issue by gsvolt** [AkronCivicHackathon/CoventryTownshipFireDeptHydrants#1]
City of Green has provided data for hydrants in South Summit area 
Latitudes and longitudes need to be extracted from this data somehow

**Comment by gsvolt** [comment]
Open Office is able to open .dbf files

**Comment by jonknapp** [comment]
looks like it's done to me!   :)

**Comment by gsvolt** [comment]
Used openoffice and succeeded at creating a .csv; closing this issue.
